# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Qiiiiiiita' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SVProgressHUD'
  pod 'RealmSwift'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'XCGLogger', '~> 7.0.0'
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'Toast-Swift', '~> 5.0.1'
  # Pods for Qiiiiiiita

  target 'QiiiiiiitaTests' do
    # Pods for testing
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

  target 'QiiiiiiitaUITests' do
    # Pods for testing
  end

end
